### PR TITLE
Add Transport NSW EFA endpoint

### PR DESCRIPTION
**Pull request by vkrause**

### CODE REVIEW

**Comment by derf** [comment]
That's a JSON-only endpoint, right? I just tried some common XML POST requests and all resulted in 403 Forbidden.

**Comment by vkrause** [comment]
This works with XML for KPublicTransport, this is an example request sent there: https://transportnsw.info/web/XML_TRIP_REQUEST2?outputFormat=XML&coordOutputFormat=WGS84[DD.ddddd]&language=en&locationServerActive=1&useRealtime=1&type_origin=coord&name_origin=151.206:-33.8831:WGS84[DD.ddddd]&type_destination=coord&name_destination=151.166:-33.935:WGS84[DD.ddddd]&itdDate=20210211&itdTime=0713&itdTripDateTimeDepArr=dep&calcNumberOfTrips=1&coordListOutputFormat=STRING

**Comment by derf** [comment]
Aaah, so there are endpoints which don't accept POST, just GET. The more you know :)

**Review by derf — APPROVED** [review]

**Comment by vkrause** [comment]
There are endpoints that need this as POST? :D
Could explain why I have some that don't seem to respond to me properly...

**Pull request merged**
