### PR TITLE
add GVH (Hannover, Germany) HAFAS mate.exe

### PR DESCRIPTION
**Pull request by derhuerst**

### CODE REVIEW

**Comment by vkrause** [comment]
looks good to me, bonus points for `region: [ "DE-NI" ]` (plus whatever else might be covered) for the coverage data

**Comment by derhuerst** [comment]
> bonus points for `region: [ "DE-NI" ]` (plus whatever else might be covered) for the coverage data

I noticed that not all of `DE-NI` is covered. For example, it doesn't even know about [Celle](https://en.wikipedia.org/wiki/Celle)'s train station.

**Comment by vkrause** [comment]
> I noticed that not all of `DE-NI` is covered. For example, it doesn't even know about [Celle](https://en.wikipedia.org/wiki/Celle)'s train station.

That's fine, this is more about "covers part of DE-NI" rather than "covers all of DE-NI", e.g. for structuring an endpoint selection UI by countries/states. That's at least how I have been filling that field so far...

**Comment by derhuerst** [comment]
> > I noticed that not all of `DE-NI` is covered. For example, it doesn't even know about [Celle](https://en.wikipedia.org/wiki/Celle)'s train station.
> 
> That's fine, this is more about "covers part of DE-NI" rather than "covers all of DE-NI", e.g. for structuring an endpoint selection UI by countries/states. That's at least how I have been filling that field so far...

Oh, then we have very different interpretations of what `realtimeCoverage` & `regularCoverage` express: I thought we "err on the careful side", by rather not including everything there's data for than covering too much.

I'm planning to let experiments like [`pan-european-public-transport`](https://github.com/derhuerst/pan-european-public-transport) (or eventually a [Linked Connections](https://linkedconnections.org)-based system) rely on `transport-apis` to figure out which API to use for which routing query. For this use case, the coverage areas should rather be too small than too large; I can see though how your use case requires the opposite.

With `anyCoverage`, I totally agree that it should be chosen generously.

**Comment by vkrause** [comment]
For the `area` key I think we have the same interpretation, so maybe we need to clarify what the `region` key means exactly, and possibly add an additional key. Either way, `area` is the crucial one, `region` can be computed from that for both interpretations if needed.

**Comment by derhuerst** [comment]
Okay, will add `region: ["DE-NI"]`.

**Comment by derhuerst** [comment]
So shall we merge this then and take care of the `region` field in another Issue?

**Comment by vkrause** [comment]
Sure, the `region` issue affects more than just this one anyway.

**Pull request merged**
