### PR TITLE
Add europe motis demo endpoint

### PR DESCRIPTION
**Pull request by 1Maxnet1**
As I wanted to use it for my own python library, I created a configuration file for the public demo instance of motis: https://europe.motis-project.de/

However there are some edge cases to deal with:
1. It covers several countries, therefore not really fitting into the de directory. However the DB endpoint does also cover several countries so maybe de directory stands for "provided from Germany" rather than "only covers Germany" so I put it there for now. Feedback and ideas welcome how to deal with this.

2. It is also not by a official transport provider but rather by the MOTIS Project itself. Therefore I followed the example of the former ulm-otp.json and called it europe-motis.json. Again ideas and feedback welcome.

3. As the coverage was completely different from the ones already existing in the repository I could not copy and paste them (as I did before) but rather I used @vkrause 's script to generate one from the iso codes. If there is anything wrong let me know as well.

@felixguendling maybe you can also check whether the configuration seems to reflect what your instance actually is for.

### CODE REVIEW

**Comment by felixguendling** [comment]
This is the GeoJSON I used for the current setup: https://gist.github.com/felixguendling/abf6e1e3669ab1faa2310adb12602b41

However, I am currently trying to add Austria (which means the server will be available again today afternoon - sry! I will try to setup a staging server next time). And of course more countries will follow in the future. So the covered area is expected to be rather volatile if I succeed in making MOTIS more efficient to be able to cover larger and larger areas. Maybe in this case, it would be easier if I add the GeoJSON file to the files that are served by the MOTIS web server.

**Comment by 1Maxnet1** [comment]
> However, I am currently trying to add Austria (which means the server will be available again today afternoon - sry!
Don't worry, let's add Austria then as well before pushing a first version of this script to the repository.

> So the covered area is expected to be rather volatile

I expect the version of motis to be way more volatile then e.g. the TRIAS version of some endpoints as well. Anyway I would still update the configuration here once in a while, to reflect changes made to the demo instance :) Serving the GeoJSON would be a nice option imho, but updating the coverage in the configuration would be okay for me as well.

**Comment by vkrause** [comment]
In general it would of course be awesome if as much as possible of the metadata maintained manually here would not be necessary and could instead be accessed on the corresponding services themselves :) Until we have that this has to do.

**Review by vkrause — APPROVED** [review]

**Comment by 1Maxnet1** [comment]
I updated the configuration to include Austria, as it is now included :)

**Pull request merged**
