### PR TITLE
DE: add bwegt TRIAS

### PR DESCRIPTION
**Pull request by 1Maxnet1**
This adds the bwegt/nvbw trias endpoint configuration and add a link to the website, where one can sign up for an API-Key

### CODE REVIEW

**Comment by 1Maxnet1** [comment]
One issue that came up with this specific client, is that a certain user-agent broke the communication with the TRIAS endpoint, as described here: https://python.tutorialink.com/post-request-to-trias-api-does-not-work-with-requests/

This seems to be a very weird issue and is rarely documented anywhere. However it would might make sense to document it in the .json as well, as else the requests will fail with 502 Error code, with no obvious reason. If anyone has any thoughts on that, or did encounter this issue as well, I would appreciate some opinions.

**Comment by derhuerst** [comment]
> […] a certain user-agent broke the communication with the TRIAS endpoint […]
> 
> This seems to be a very weird issue and is rarely documented anywhere. However it would might make sense to document it in the .json as well […].

I agree, this is very relevant. But I'm don't know how this would scale; For example, the VBB HAFAS APIs blocks dozens, if not hundreds, specific `User-Agent`s by now. How would we ever keep these lists up-to-date?

**Comment by 1Maxnet1** [comment]
> I agree, this is very relevant. But I'm don't know how this would scale; For example, the VBB HAFAS APIs blocks dozens, if not hundreds, specific `User-Agent`s by now. How would we ever keep these lists up-to-date?

Oh okay. I wasn't aware that the problem is that huge ... Uf.

We could use the Markdown format to note this issue and instead of documenting all known blocked or working headers we could mention some (prominent) examples which work or which don't.

I also contacted NVBW regarding this issue. Will report back what they might say..

**Comment by 1Maxnet1** [comment]
Also if this issue is not specific to TRIAS-Endpoints we might also want to discuss it in general in a separate Issue, don't we?

**Comment by derhuerst** [comment]
> Also if this issue is not specific to TRIAS-Endpoints we might also want to discuss it in general in a separate Issue, don't we?

Sure, if there's more you would like to discuss, open an Issue! 😊 Otherwise we can just merge a first version.

**Review by derhuerst — APPROVED** [review]

**Comment by 1Maxnet1** [comment]
> > Also if this issue is not specific to TRIAS-Endpoints we might also want to discuss it in general in a separate Issue, don't we?
> 
> Sure, if there's more you would like to discuss, open an Issue! blush Otherwise we can just merge a first version.

This PR is fine from my side. Will open another issue to discuss the user-agent problem and how to deal with it. But imo it is not a stopper for this PR.

**Pull request merged**
